const quotes = [
    "Respira fundo, o momento passa.",
    "Coragem e calma podem andar juntas.",
    "Um passo pequeno já é progresso.",
    "Tu não és a tua ansiedade.",
    "O medo diminui quando te moves.",
    "Hoje é um bom dia para tentar.",
    "Fala devagar, o teu tempo é válido.",
    "Cada tentativa é uma vitória.",
    "Ser gentil contigo é um acto de coragem.",
    "O desconforto não dura para sempre.",
    "O teu valor não depende da opinião alheia.",
    "Tu consegues, um passo de cada vez.",
    "A ansiedade mente; tu escolhes a verdade.",
    "A calma nasce na tua respiração.",
    "Confia no processo, não na pressa.",
    "O teu ritmo é suficiente.",
    "Olha para a frente, não para o medo.",
    "A coragem cresce quando repetes.",
    "Tu já passaste por momentos difíceis.",
    "A tua voz merece ser ouvida.",
    "O agora é o único lugar seguro.",
    "Avançar mesmo com medo é valentia.",
    "Pequenas conquistas somam grandes mudanças.",
    "Hoje podes ser mais gentil contigo.",
    "O teu corpo pode relaxar, mesmo agora.",
    "A ansiedade sobe, mas também desce.",
    "Respira, sente o chão, segue.",
    "Não precisas ser perfeito para crescer.",
    "Tu és mais forte do que pensas.",
    "Um olhar gentil muda o dia.",
    "A prática transforma o desconforto.",
    "A tua calma é treinável.",
    "Cada encontro é uma oportunidade.",
    "A tua presença é suficiente.",
    "Tu és capaz de te expressar.",
    "O medo não decide por ti.",
    "Escolhe a coragem, mesmo pequena.",
    "Esta sensação vai passar.",
    "O teu esforço conta.",
    "Tu podes recomeçar sempre.",
    "Um passo hoje, dois amanhã.",
    "O silêncio interno pode acalmar.",
    "Foca na respiração, volta ao presente.",
    "Tu és digno de respeito.",
    "O teu progresso importa.",
    "A ansiedade não define quem és.",
    "Confia no teu treino.",
    "Aceita o desconforto e avança.",
    "Tudo começa com um pequeno sim.",
    "Tu és mais que os teus medos."
];

function getRandomQuote() {
    const index = Math.floor(Math.random() * quotes.length);
    return quotes[index];
}

export { quotes, getRandomQuote };
