const quotes = [
    "Respira fundo, o momento passa.",
    "Coragem e calma podem andar juntas.",
    "Um passo pequeno ja e progresso.",
    "Tu nao es a tua ansiedade.",
    "O medo diminui quando te moves.",
    "Hoje e um bom dia para tentar.",
    "Fala devagar, o teu tempo e valido.",
    "Cada tentativa e uma vitoria.",
    "Ser gentil contigo e um ato de coragem.",
    "O desconforto nao dura para sempre.",
    "O teu valor nao depende da opiniao alheia.",
    "Tu consegues, um passo de cada vez.",
    "A ansiedade mente, tu escolhes a verdade.",
    "A calma nasce na tua respiracao.",
    "Confia no processo, nao na pressa.",
    "O teu ritmo e suficiente.",
    "Olha a frente, nao para o medo.",
    "A coragem cresce quando repetes.",
    "Tu ja passaste por momentos dificeis.",
    "A tua voz merece ser ouvida.",
    "O agora e o unico lugar seguro.",
    "Avancar mesmo com medo e valentia.",
    "Pequenas conquistas somam grandes mudancas.",
    "Hoje podes ser mais gentil contigo.",
    "O teu corpo pode relaxar, mesmo agora.",
    "A ansiedade sobe, mas tambem desce.",
    "Respira, sente o chao, segue.",
    "Nao precisas ser perfeito para crescer.",
    "Tu es mais forte do que pensas.",
    "Um olhar gentil muda o dia.",
    "A pratica transforma o desconforto.",
    "A tua calma e treinavel.",
    "Cada encontro e uma oportunidade.",
    "A tua presenca e suficiente.",
    "Tu es capaz de te expressar.",
    "O medo nao decide por ti.",
    "Escolhe a coragem, mesmo pequena.",
    "Esta sensacao vai passar.",
    "O teu esforco conta.",
    "Tu podes recomecar sempre.",
    "Um passo hoje, dois amanha.",
    "O silencio interno pode acalmar.",
    "Foca na respiracao, volta ao presente.",
    "Tu es digno de respeito.",
    "O teu progresso importa.",
    "A ansiedade nao define quem es.",
    "Confia no teu treino.",
    "Aceita o desconforto e avanca.",
    "Tudo comeca com um pequeno sim.",
    "Tu es mais que os teus medos."
];

function getRandomQuote() {
    const index = Math.floor(Math.random() * quotes.length);
    return quotes[index];
}

export { quotes, getRandomQuote };
